'use strict';
const $=s=>document.querySelector(s);
const spreadNames={2:'雙牌組合',3:'三牌故事',9:'九宮格',36:'Grand Tableau'};
let spread=3,pile=[],selected=[],started=false,activeReading=null;
const storageKey='anna-readings-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cardHTML(c){return `<button class="card" data-card="${c.id}" aria-label="${c.id} ${c.name}，查看牌義"><span class="corners"><span>${String(c.id).padStart(2,'0')}</span><span>${c.suit}</span></span><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="45" stroke-opacity=".18"/><path d="${c.path}"/></svg><span class="card-name">${c.name}</span><span class="card-en">${c.en.toUpperCase()}</span></button>`;}
function randomBelow(n){const bound=Math.floor(4294967296/n)*n;const v=new Uint32Array(1);do{crypto.getRandomValues(v);}while(v[0]>=bound);return v[0]%n;}
function shuffleCards(){const a=[...CARDS];for(let i=a.length-1;i>0;i--){const j=randomBelow(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function slotLabel(i){return spread===36?`${i+1} · ${CARDS[i].name}宮`:spread===9?(i===4?'中心 · 核心主題':`位置 ${i+1}`):spread===2?['主題','補充與修飾'][i]:['故事起點','核心情境','後續線索'][i];}
function renderSlots(){const slots=$('#slots');slots.className=`slots spread-${spread}`;slots.innerHTML=Array.from({length:spread},(_,i)=>`<div class="slot">${selected[i]?cardHTML(selected[i]):`<div class="empty-card" aria-label="位置 ${i+1}，尚未抽牌">${i+1}</div>`}<span class="slot-label">${slotLabel(i)}</span></div>`).join('');}
function reset(){started=false;pile=[];selected=[];activeReading=null;$('#result').hidden=true;$('#draw-zone').hidden=true;$('#start-note').hidden=false;$('#progress').textContent='準備好，再開始';$('#spread-title').textContent=spreadNames[spread];$('#shuffle').textContent='✦ 洗牌，開始探索';$('#person-wrap').hidden=spread!==36;renderSlots();}
function start(){pile=shuffleCards();selected=[];activeReading={question:$('#question').value.trim(),topic:$('#topic').value,person:Number($('#person').value)};started=true;$('#result').hidden=true;$('#start-note').hidden=true;$('#draw-zone').hidden=false;$('#shuffle').textContent='↻ 重新洗牌';$('#deck').innerHTML=pile.map((_,i)=>`<button class="card back" data-pick="${i}" aria-label="抽取第 ${i+1} 張牌"><span class="back-star">✧</span></button>`).join('');renderSlots();updateProgress();}
function updateProgress(){$('#progress').textContent=`已抽 ${selected.length} / ${spread} 張`;$('#draw-tip').textContent=`憑直覺，選第 ${selected.length+1} 張牌。`;}
function pick(i){if(!started||!pile[i]||selected.length>=spread)return;selected.push(pile[i]);pile[i]=null;const btn=$(`#deck [data-pick="${i}"]`);if(btn){btn.classList.add('picked');btn.disabled=true;}renderSlots();updateProgress();if(selected.length===spread){started=false;$('#draw-zone').hidden=true;renderResult();$('#progress').textContent='故事已展開 · 點牌查看牌義';}}
const pairOverrides={'1-27':'書面消息正在傳來，留意通知、文件或聯絡。','24-25':'感情與承諾連在一起，適合確認關係中的共同約定。','25-24':'既有承諾帶有情感與熱情，關注合作或關係的感受。','34-23':'資源可能被小問題持續消耗，檢查零碎支出與流失。','23-34':'焦慮或損耗與金錢流動有關，先釐清實際收支。','21-33':'阻礙出現解決線索，找出真正能突破限制的關鍵。','33-21':'解決方式仍受限制，先確認阻擋它的具體條件。','6-27':'資訊尚不清楚，文件或訊息需要進一步核實。','18-25':'可靠的夥伴與承諾相連，合作關係值得清楚約定。','13-31':'新的起步帶有活力，適合把小成果具體化。','35-36':'長期投入伴隨責任，留意持續承擔的負荷。','8-13':'一個階段收尾後出現新起點，先整理再開始。','27-14':'書面訊息需要謹慎核實，檢查細節與對方動機。'};
function pair(a,b){return pairOverrides[`${a.id}-${b.id}`]||`${a.name}指向「${a.noun}」，${b.name}補充「${b.modifier}」的特質。可連讀為：${b.modifier}${a.noun}。`;}
function linesFor(cards,n,person){const lines=[];const add=(title,list)=>lines.push({title,text:list.slice(0,-1).map((c,i)=>pair(c,list[i+1])).join(' ')});if(n===2)add('雙牌連讀 · 主題與修飾',cards);if(n===3){add('左 → 右 · 故事的發展',cards);lines.push({title:`中心線索 · ${cards[1].name}`,text:cards[1].meaning+' '+cards[1].advice});}if(n===9){lines.push({title:`中心牌 · ${cards[4].name}`,text:cards[4].meaning});for(let i=0;i<3;i++)add(['上列 · 背景線索','中列 · 當前焦點','下列 · 實際落點'][i],cards.slice(i*3,i*3+3));for(let i=0;i<3;i++)add(['左列 · 前因','中列 · 主要軸線','右列 · 後續線索'][i],[cards[i],cards[i+3],cards[i+6]]);add('斜線 · 補充觀察',[cards[0],cards[4],cards[8]]);add('另一條斜線',[cards[2],cards[4],cards[6]]);}if(n===36){const idx=cards.findIndex(c=>c.id===person),row=Math.floor(idx/9),col=idx%9;lines.push({title:`指示牌 · ${CARDS[person-1].name}`,text:`位於第 ${idx+1} 宮「${CARDS[idx].name}」，可用這個宮位觀察當事人目前的主題。${pair(cards[idx],CARDS[idx])}`});for(const [label,dr,dc] of [['左側線索',0,-1],['右側線索',0,1],['上方線索',-1,0],['下方線索',1,0]]){const nr=row+dr,nc=col+dc;if(nr>=0&&nr<4&&nc>=0&&nc<9){const c=cards[nr*9+nc];lines.push({title:`${label} · ${c.name}`,text:pair(cards[idx],c)});}}for(const id of [24,25,34,35]){const i=cards.findIndex(c=>c.id===id);lines.push({title:`${CARDS[id-1].name}落在 ${CARDS[i].name}宮`,text:pair(CARDS[id-1],CARDS[i])});}lines.push({title:'逐宮探索',text:'點選任一張牌，可查看它落入的宮位及組合提示。此處呈現宮位與人物周邊的入門觀察，不是完整大牌陣預測。'});}return lines;}
function contextAdvice(topic,cards){const keys={love:'觀察彼此的溝通、界線與約定，將推測轉成可以確認的對話。',work:'將線索轉成可確認的進度、合作條件與下一步任務。',money:'對照實際收支、契約與可用資源，找出需要查證的細節。',general:'找一項可以向現實查證的線索，再決定下一步。'};const focus=cards.length===9?cards[4]:cards[Math.floor(cards.length/2)];return `${keys[topic]||keys.general} 以${focus.name}為觀察點：${focus.advice}`;}
function resultText(){const a=activeReading;return [`ANNA · ${spreadNames[spread]}`,a.question||'未設定問題',selected.map(c=>`${c.id} ${c.name}`).join(' → '),...linesFor(selected,spread,a.person).map(l=>l.title+'\n'+l.text),contextAdvice(a.topic,selected),'以上為程式化牌義組合提示，供娛樂與自我整理參考。'].join('\n\n');}
function renderResult(){const a=activeReading;$('#result').hidden=false;$('#result').innerHTML=`<div class="result-header"><div class="eyebrow">THE STORY IN YOUR CARDS</div><h2>你的牌，正在說什麼？</h2><p>${esc(a.question||'這次，讓牌替你開啟一個觀察角度。')}</p></div>${linesFor(selected,spread,a.person).map(l=>`<div class="reading-line"><b>${esc(l.title)}</b><p>${esc(l.text)}</p></div>`).join('')}<div class="reading-line"><b>把線索帶回生活</b><p>${esc(contextAdvice(a.topic,selected))}</p></div><p class="privacy">依內建牌義規則組合，未使用 AI 分析問題；可依現實情境調整理解。</p><div class="actions"><button id="save">♡ 儲存這次紀錄</button><button id="copy">複製解讀</button><button id="download">下載文字</button></div>`;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function readHistory(){try{const data=JSON.parse(localStorage.getItem(storageKey)||'[]');return Array.isArray(data)?data.filter(x=>x&&spreadNames[x.spread]&&Array.isArray(x.cards)&&x.cards.length===x.spread&&new Set(x.cards).size===x.spread&&x.cards.every(id=>Number.isInteger(id)&&id>=1&&id<=36)&&typeof x.id==='string').slice(0,100):[];}catch{return [];}}
function save(){const list=readHistory();list.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),spread,cards:selected.map(c=>c.id),...activeReading,note:''});try{localStorage.setItem(storageKey,JSON.stringify(list.slice(0,100)));toast('已儲存到我的紀錄');$('#save').disabled=true;}catch{toast('無法儲存：瀏覽器儲存空間不可用');}}
function showHistory(){const list=readHistory();$('#history-list').innerHTML=list.length?list.map(r=>`<article class="history-entry"><small>${esc(new Date(r.date).toLocaleString('zh-TW'))} · ${spreadNames[r.spread]}</small><h3>${esc(r.question||'未設定問題')}</h3><p>${r.cards.map(id=>CARDS[id-1].name).join(' → ')}</p><label for="note-${r.id}">後來的觀察</label><textarea id="note-${r.id}" data-note="${esc(r.id)}" maxlength="1200" placeholder="記下後來的發展…">${esc(r.note||'')}</textarea><button class="text-button" data-restore="${esc(r.id)}">重新查看 ↗</button><button class="text-button" data-delete="${esc(r.id)}">刪除此筆</button></article>`).join(''):'<div class="empty-state">還沒有紀錄。抽完牌後，按「儲存這次紀錄」。</div>';$('#clear-history').hidden=!list.length;}
function changeView(view){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view);document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));if(view==='history')showHistory();window.scrollTo({top:0,behavior:'smooth'});}
function showCard(id){const c=CARDS[id-1];let house='';if(!$('#reading').hidden&&selected.length===36){const idx=selected.findIndex(x=>x.id===id);if(idx>=0)house=`<p><b>第 ${idx+1} 宮 · ${CARDS[idx].name}</b><br>${esc(pair(c,CARDS[idx]))}</p>`;}$('#modal-content').innerHTML=`<div class="modal-layout"><div>${cardHTML(c)}</div><div><div class="eyebrow">CARD ${String(id).padStart(2,'0')} · ${c.suit}</div><h2>${c.name} ${c.en}</h2><p>${c.keywords}</p><p>${c.meaning}</p><p>${c.advice}</p>${house}</div></div>`;$('#card-modal').showModal();}
function renderLibrary(term=''){const q=term.toLowerCase().trim();const cards=CARDS.filter(c=>`${c.id} ${c.name} ${c.en} ${c.keywords}`.toLowerCase().includes(q));$('#card-library').innerHTML=cards.length?cards.map(c=>`<div class="library-item">${cardHTML(c)}<small>${c.keywords}</small></div>`).join(''):'<p>找不到符合的牌，試試其他關鍵字。</p>';}
$('#shuffle').addEventListener('click',start);$('#auto-draw').addEventListener('click',()=>{for(let i=0;i<pile.length&&started;i++)if(pile[i])pick(i);});
$('#search').addEventListener('input',e=>renderLibrary(e.target.value));$('#card-modal .close').addEventListener('click',()=>$('#card-modal').close());$('#card-modal').addEventListener('click',e=>{if(e.target===$('#card-modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)changeView(b.dataset.view);if(b.dataset.spread){spread=Number(b.dataset.spread);document.querySelectorAll('[data-spread]').forEach(x=>x.classList.toggle('selected',x===b));reset();}if(b.dataset.question){$('#question').value=b.dataset.question;$('#topic').value=b.dataset.topic;}if(b.dataset.pick!==undefined)pick(Number(b.dataset.pick));if(b.dataset.card&& !b.closest('#card-modal'))showCard(Number(b.dataset.card));if(b.id==='save')save();if(b.id==='copy'){try{await navigator.clipboard.writeText(resultText());toast('已複製解讀');}catch{toast('無法複製，請使用下載文字');}}if(b.id==='download'){const url=URL.createObjectURL(new Blob([resultText()],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='ANNA-reading.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(b.dataset.restore){const r=readHistory().find(x=>x.id===b.dataset.restore);if(!r)return;spread=r.spread;document.querySelectorAll('[data-spread]').forEach(x=>x.classList.toggle('selected',Number(x.dataset.spread)===spread));reset();selected=r.cards.map(id=>CARDS[id-1]);activeReading={question:r.question,topic:r.topic,person:r.person||28};$('#question').value=r.question||'';$('#topic').value=r.topic||'general';$('#person').value=activeReading.person;$('#start-note').hidden=true;$('#progress').textContent='已載入儲存紀錄';renderSlots();renderResult();changeView('reading');}if(b.dataset.delete&&confirm('刪除這筆紀錄？')){try{localStorage.setItem(storageKey,JSON.stringify(readHistory().filter(x=>x.id!==b.dataset.delete)));showHistory();}catch{toast('無法刪除紀錄');}}if(b.id==='clear-history'&&confirm('清除所有紀錄？此操作無法還原。')){try{localStorage.removeItem(storageKey);showHistory();}catch{toast('無法清除紀錄');}}});
document.addEventListener('change',e=>{if(e.target.dataset.note){const list=readHistory(),r=list.find(x=>x.id===e.target.dataset.note);if(r){r.note=e.target.value;try{localStorage.setItem(storageKey,JSON.stringify(list));toast('觀察已儲存');}catch{toast('無法儲存觀察');}}}});
reset();renderLibrary();
